endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: true

zuul:
  routes:
    workspaces-api:
      path: /workspaces-service/**
      servicId: workspace-api
      strip-prefix: true
    employees-api:
      path: /employees-service/**
      serviceId: employees-api
      strip-prefix: true

